#include <string>

/**
 * You are given two strings "s" and "t".
 *
 * String "t" is generated by random shuffling string "s" and then add one more letter at a random
 * position.
 *
 * Return the letter that was added to "t".
 *
 * ! t.length == s.length + 1
 */

class Solution
{
public:
    char findTheDifference(std::string s, std::string t)
    {
        // approach: xor, a ^ b ^ a = (a ^ a) ^ b = 0 ^ b = b
        char result = 0;
        for (const auto& c : s) {
            result ^= c;
        }
        for (const auto& c : t) {
            result ^= c;
        }
        return result;
    }
};
